business-name: P W Angling
business-tel: 01603 619381
business-email: peter@pwangling.co.uk
business-tagline: For All Your Angling Needs
business-address:
  street: 59 Long John Hill
  city: Norwich
  postcode: NR1 2JJ
opening-times:
  mon: Monday 8.30am-5.30pm
  tues: Tuesday 8.30am-5.30pm
  weds: Wednesday 8.30am-5.30pm
  thurs: Thursday 8.30am-5.30pm
  fri: Friday 8.30am-5.30pm
  sat: Saturday 8.30am-5pm
  sun: Sunday closed

